# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20170723_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='music',
            field=models.FileField(default=1, upload_to='product', verbose_name='music'),
            preserve_default=False,
        ),
    ]
