# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20170726_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='texts',
            field=models.TextField(max_length=5000, verbose_name='article'),
        ),
    ]
