# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20170726_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(default=1, upload_to='product', verbose_name='video'),
            preserve_default=False,
        ),
    ]
